# Generated by Django 3.0.5 on 2020-04-22 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guia', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='city',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='place',
            name='adress',
            field=models.CharField(default='Sem endereço', max_length=180),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='phone',
            field=models.CharField(default='Sem telefone', max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='city',
            name='id',
            field=models.CharField(max_length=4, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='id',
            field=models.CharField(max_length=4, primary_key=True, serialize=False, unique=True),
        ),
    ]
