# Generated by Django 3.0.5 on 2020-04-22 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guia', '0002_auto_20200422_0259'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['name'], 'verbose_name_plural': 'cities'},
        ),
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
