# Generated by Django 3.0.5 on 2020-04-22 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guia', '0003_auto_20200422_0431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterUniqueTogether(
            name='place',
            unique_together={('name', 'city', 'service')},
        ),
    ]
